### ISSUE TITLE
undefining the allocator of T_DATA class FastContainers::PriorityQueue

### ISSUE THREAD

**Issue by starbeast** [boborbt/priority_queue_cxx#7] opened 2023-01-26 12:06 UTC
First of all, thanks for the gem!

The warning is seen when an instance of FastContainers::PriorityQeueu is initialized. If I understand correctly `rb_undef_alloc_func(PriorityQueue)` in the `Init_fast_containers` function should do the trick. Ruby demands that T_DATA objects must either define an allocator or undefine the
default one.

**Comment by boborbt** [comment] 2023-01-26 13:12
Hi starbeast, I cannot reproduce the problem, this is the total of the output I can see on my terminal when I use the library:

```ruby
=> true
irb(main):005:0> q = FastContainers::PriorityQueue.new(:max)
=> #<FastContainers::PriorityQueue:0x0000000104787058>
irb(main):006:0> q.push("largest", 10)
=> #<FastContainers::PriorityQueue:0x0000000104787058>
irb(main):007:0> q.push("smallest", 5)
=> #<FastContainers::PriorityQueue:0x0000000104787058>
irb(main):008:0> q.top      # =>  "largest"
=> "largest"
irb(main):009:0> q.top_key  # => 10
irb(main):010:0> q.pop
=> "largest"
```

Are you able to provide a minimal test case to investigate the issue?

**Comment by boborbt** [comment] 2023-01-26 14:13
Ok, I'm able to reproduce the problem (it only happens on ruby 3.2)

**Comment by boborbt** [comment] 2023-01-26 14:28
I just pushed v0.3.6 which fixes the problem. I'm closing the issue.

**Closed by boborbt** 2023-01-26 14:28 UTC
